apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: test-image
spec:
  tag: <IMAGE-TAG>
  serviceAccount: kpack-service-account
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/projectriff/fats
      revision: main
    subPath: applications/uppercase/node
