apiVersion: bindings.projectriff.io/v1alpha1
kind: ImageBinding
metadata:
  name: test-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
  containerName: test-container
  provider:
    name: petclinic
    apiVersion: build.projectriff.io/v1alpha1
    kind: Application
