apiVersion: service.binding/v1alpha1
kind: ServiceBinding
metadata:
  name: account-db
spec:
  type: mysql
  application:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
    containers:
    - test-container
  service:
    apiVersion: service.binding/v1alpha1
    kind: ProvisionedService
    name: account-db

---
apiVersion: service.binding/v1alpha1
kind: ProvisionedService
metadata:
  name: account-db
spec:
  binding:
    name: account-db-service
#status: # status is created by the ProvisionedService controller, but implements the duck-type
#  binding:
#    name: account-db-service

---
apiVersion: v1
kind: Secret
metadata:
  name: account-db-service
type: Opaque
stringData:
  host: localhost
  jdbcUrl: jdbc:mysql://localhost:3306/default?user=root&password=
  name: default
  password: ""
  port: "3306"
  uri: mysql://root:@localhost:3306/default?reconnect=true
  username: root
